### ISSUE TITLE
AK60-6 support

### ISSUE THREAD

**Issue by jocacace** [dfki-ric-underactuated-lab/mini-cheetah-tmotor-can#1]
Hi guys,

Is this software supporting AK60-6 motors?

**Comment by vyas-shubham** [comment]
Hello @jocacace 

Yes! The software does support AK80-6. The list of supported motors can be seen in the header file [here](https://github.com/dfki-ric-underactuated-lab/mini-cheetah-tmotor-can/blob/f0bfd286298227235ebba4147c2b3e05eb0da501/include/motor_driver/MotorDriver.hpp#L44). These are:
- AK80-6 V1
- AK80-6 V1.1
- AK80-6 V2
- AK80_9 V1.1
- AK80_9 V2

As you can see, there are 3 different firmware for AK80-6 provided by T-Motors/Cubemars. Depending on the firmware version the conversion Constants are different and can be seen [here](https://github.com/dfki-ric-underactuated-lab/mini-cheetah-tmotor-can/blob/f0bfd286298227235ebba4147c2b3e05eb0da501/include/motor_driver/MotorDriver.hpp#L97) in the header file.

**Comment by jocacace** [comment]
Dear @vyas-shubham,

Thank you for the quick reply. I was wondering if the AK60 can be supported (i would add them). In the file you listed me there are contained only parameters, so I was wondering if the protcol could be considered the same.

**Comment by vyas-shubham** [comment]
I'm sorry. I misread it as AK80-6. The current software does not support AK60-6 as we don't have any drive units for testing/validation. However, looking at the [AK-Series Manual](https://store.cubemars.com/images/file/20211201/1638329381542610.pdf) from T-Motors, it does seem like all of them use the same communication protocol. So this should indeed work quite easily after adding the motor to the list along with its parameters. 

I'd highly recommend creating a pull request if you do that so that others could also benefit from this addition!

**Comment by vyas-shubham** [comment]
Hi @jocacace 

I recently added support for another Motor from T-Motor/CubeMars: Ak10-9. Do see [this commit](https://github.com/dfki-ric-underactuated-lab/mini-cheetah-tmotor-can/commit/13a2f537b10b7321b4825a4d8a5436b92c11a1e3) for info on what changes are to be made to add a new motor.

Hopefully, this is helpful in adding support for the motor you wanted to add. Also, if you prefer, I can add the parameters from the manual from CubeMars [here](https://store.cubemars.com/images/file/20220307/1646619452473352.pdf) (see Page 49-50). Then you can try the parameters to see if they work. 

Similarly, we have a python driver for the same motors/hardware [here](https://github.com/dfki-ric-underactuated-lab/mini-cheetah-tmotor-python-can) with its pip package [here](https://pypi.org/project/mini-cheetah-motor-driver-socketcan/)

**Comment by vyas-shubham** [comment]
@jocacace For a recent community addition (motor AK70-10), see [this](https://github.com/dfki-ric-underactuated-lab/mini-cheetah-tmotor-can/pull/2) pull request.

**Comment by vyas-shubham** [comment]
Closed due to inactivity.
