### ISSUE TITLE
Order of motor control commands initialization

### ISSUE THREAD

**Issue by omerwil** [dfki-ric-underactuated-lab/mini-cheetah-tmotor-can#4]
Hello,

Your initialization of motors is done by entering control mode and then setting zero position

When I'm doing it like that,  motor is getting confused right after entering control mode and moves fast to undefined position - this jump is probably because of the last position it remembers.
If I'm setting zero position first and then entering control mode, the motor is "locked" on its current position and waiting for commands.
Most important thing is that i must turn power off and on for the motor in order to initiate it correctly. It's necessary to do it after every cycle of using motor, especially after exit control mode.

Probably i miss something, do you also need to power it off and on?

Thank you!

**Comment by vyas-shubham** [comment]
Hi @omerwil,

We've had an issue with the "initial kick" (as described [here](https://github.com/dfki-ric-underactuated-lab/mini-cheetah-tmotor-can#known-issues) in the Readme). But we mostly observe it when we have 2 motors on the same CAN bus. For a single motor, it goes quite well. For a lengthy example of our usage with a single motor see [this repo](https://github.com/dfki-ric-underactuated-lab/torque_limited_simple_pendulum).

When you set zero position before initializing the motor, does it go better for you? I could not understand this from your message. You say the motor is "locked" in the current position. What does this mean? It doesn't respond to any command or does it try to maintain its current position?

Thank you!
Shubham

**Comment by omerwil** [comment]
Hey @vyas-shubham,

Thank you for replying.
I'll give it a try on a single motor (always tested multiple motors on the same can-bus)

When setting zero position before entering control it works fine:
I'm keep setting zero position and waiting for motor to reply its current position and only after I'm getting ~zero, then I'm sending control mode. the motor maintains it's current position unless I'm sending a new command to move.
Hope it was clear.

Thanks again,
Omerr

**Comment by vyas-shubham** [comment]
Thanks for the clarification. We usually have max 3 motors on the same CAN bus to maintain 1Khz frequency. However, most of our systems only have 1-2 motors at the moment. 

The way I understand you is that if I set zero position before enabling control mode, it solves the "initial kick" problem, is that correct?

**Comment by omerwil** [comment]
That's correct. I'll test it again the way you did and let you know. Thank you so much
Omer

**Comment by vyas-shubham** [comment]
Thanks a lot for your solution to the initial kick issue. I will test it on the motors we have here at DFKI. Once I can experimentally validate the solution (setZero before initializing the motor), I will update the driver.

**Comment by vyas-shubham** [comment]
@omerwil I (finally) got time to test this on the real system. Unfortunately, zeroing before enabling the motor still resulted in kicking behavior in some of the motors we have here. Thus, I couldn't add this as a fix.

In the process, I found a fix that works without fail until now: sending an all-zero command before disabling. The current working theory is that the motor "remembers" the last command. And this causes an initial kick as the motor controller starts. The fix is then to set the last command to zero so that this does not happen. For the user, the behavior does not change as zero command + disable is the same as disabling.

**Comment by omerwil** [comment]
Hi @vyas-shubham 
I agree with the theory you mentioned - i got the same results.
In order to overcome the time i'm spending while computer restarts with the motor, i seperated the power input from the motor so it's much easier to reset it without waiting to software restart.
 thank you and good luck :)

**Comment by vyas-shubham** [comment]
@omerwil You're welcome. With the new update with the fix, I haven't seen any initial kicks/jerks yet and I tested it quite a bit yesterday. So I'm pretty confident about the fix now. So you shouldn't need the restarts in between experiments now. The python/pip driver is also updated with the fix as well.

We have an emergency stop which we were using as an "on/off switch" until now for the same reason. Now we can stop using it as a switch and go back to using it only for emergencies. ;)
