### ISSUE TITLE
AK80-64 Parameter configuartion

### ISSUE THREAD

**Issue by runjanna26** [dfki-ric-underactuated-lab/mini-cheetah-tmotor-can#7]
I'm looking for AK80-64 parameter configurations such as P_MAX, P_MIN, V_MAX, and V_MIN.

**Comment by vyas-shubham** [comment]
See the actuator driver manual from this webpage for the parameters: https://store.cubemars.com/goods.php?id=1143

**Comment by runjanna26** [comment]
My situation is in this forum [https://forum.mybotshop.de/t/ak80-64-mit-mode-cannot-control/414](url)

I have followed your code but didn't work for my AK80-64.

**Comment by vyas-shubham** [comment]
Were you able to enable/disable the motor and get any data back? Else I'd suggest checking the CAN connection and the motor mode configuration.

**Comment by runjanna26** [comment]
Thank you for the suggestion.
How to check the CAN connection and motor mode configuration? Can you give me more detail?

**Comment by vyas-shubham** [comment]
I would suggest reading the T-Motor's driver manual given in the link I posted earlier for the motor mode configuration tutorial (Support and Downloads->AK80-64 AK Series actuator driver manual v1.0.9). You have to use their software which runs only on Windows. I assume the motors initially come with MIT mode by default. This was the case for our motors from T-motor. We do not have an AK80-64 so I cannot test the specific parameters for this motor.

As for CAN, I would recommend using an oscilloscope, or tutorials for CAN with Arduino to get an introduction to wiring the CAN network.

**Comment by vyas-shubham** [comment]
I just saw that you're using an STM32 board for communication with the motor. This driver is written for communication using a Linux PC with a USB-to-CAN converter that supports SocketCAN. I would not suggest running this code or using the driver for STM32 as it depends heavily on having linux.

**Comment by runjanna26** [comment]
Thank you
